### ISSUE TITLE
Add tabular figures

### ISSUE THREAD

**Issue by cssobral2013** [RedHatOfficial/Overpass#59]
It wouldn't be a bad idea to add tabular figures to this font.

**Comment by DelveFonts** [comment]
@cssobral2013 Thank you. That is a good suggestion. May I suggest using the numerals within Overpass Mono, in the meantime? They are tabular by default, since it is monospaced.

**Comment by cssobral2013** [comment]
Specifically for what I mean by 'tabular figures', it means 0-9 and all currencies.

**Comment by morrisoz** [comment]
This would be a fantastic addition.

**Comment by t-rapp** [comment]
It seems that tabular figures are available in version 4.0 of this font, which is great!
