### ISSUE TITLE
Please build release 3.0.4

### ISSUE THREAD

**Issue by gforrest-bw** [RedHatOfficial/Overpass#75]
Commented this on another issue, but I'm not sure it was seen.

I appreciate the work done to fix the line height rendering issues in PR #66. The repo may list v3.0.4 which "officially" releases this fix, but the webfonts have not been built in the last 2 years, so there's still no way for anyone without licensed software to use the font. Google Fonts doesn't seem to have updated either.

Since the work has already been put in, it would be shame to let it go to waste! If nothing else, can you build the webfonts using the required software and push them to the repo so we can self-host a fixed version?

If I'm mistaken, please direct me to a copy of the built font and I'll be on my way!

**Comment by kosmosjamaa** [comment]
any update on the build that fixes the line height issue?

**Comment by iLaurens** [comment]
Thanks for spotting this, I updated to 3.0.4 hoping the line-height issue was fixed. If there are instructions how to build the font from the source folder I'd be happy to assist.

**Comment by gutdingwillweilehaben** [comment]
Hi, I'm also looking for the latest build of the font. Is there already a new build available?

**Comment by stephenreid321** [comment]
I'm also looking for the latest build!

**Comment by kosmosjamaa** [comment]
@stephenreid321 @gutdingwillweilehaben  here are generated font files from the latest glyps. i dont have push access so i'll just drop a mediafire link https://www.mediafire.com/folder/eymuy8imqcpgx/

**Comment by stephenreid321** [comment]
Thanks!

**Comment by gforrest-bw** [comment]
@kosmosjamaa May I suggest forking the repo and issuing a PR with these files included? MediaFire is not the most convenient method of downloading (they require you to pay to download multiple files at once... in 2020!)

I'll do it once I have them all downloaded if you'd like, just figured as you were the one that finally corrected the situation, you might want to be the one to contribute the fix!

**Comment by teleyinex** [comment]
Any updates on this? Otherwise I'm happy to send the PR myself :-) Just downloaded all the fonts.

**Comment by teleyinex** [comment]
Quick follow up, as it was easy, I've sent you a PR: https://github.com/RedHatOfficial/Overpass/pull/84

All the acknowledgments should go to @kosmosjamaa!

**Comment by michaelfaith** [comment]
Will this be merged in soon?  Our corporation was planning to adopt this font as part of its design standard, and this line height issue has become a blocking issue.

**Comment by 70nyIT** [comment]
I highly suggest you guys to re-built it. I have been struggling a lot as I was importing the font from Google Fonts, and having issue with the line-height too. I think that Google Fonts gets the latest build and not the actual files in the repo. You can see it in this codesandbox, where you clearly see text is not centered in the button
https://codesandbox.io/s/unruffled-vaughan-zvwq9

If I clone the repo files, of course, everything is fine

**Comment by michaelfaith** [comment]
@70nyIT there's already an issue in Google Fonts' github to update with the latest build.  They don't automatically injest what was built here.  https://github.com/google/fonts/issues/2665

**Comment by 70nyIT** [comment]
yes, seen that issue @michaelfaith. What's sure is that downloading the latest build without the latest file in it can be confusing, like have been for me and other users

**Comment by michaelfaith** [comment]
Oh, do you mean the zip attached to the 3.0.4 tag? That's true. Maybe they should create a new tag?

**Comment by 70nyIT** [comment]
yes, exactly. If you see the "release" section it bring you to this page
https://github.com/RedHatOfficial/Overpass/releases/tag/3.0.4

I think to avoid confusion a 3.0.5 should be released with the latest build

**Comment by michaelfaith** [comment]
Agreed, that would be the safest way to avoid confusion.

**Comment by michaelfaith** [comment]
@70nyIT they made the 3.0.5 release today, if you want to pull it now.
